services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "5555:5555"
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=10.211.55.4:4317
      - OTEL_NODE_RESOURCE_DETECTORS=env,host,os
      - SERVICE_NAME=app-service
      - INSECURE_MODE=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/localzone:/etc/localzone:ro
    networks:
      - app-network
  
  #https://signoz.io/docs/userguide/collect_docker_logs/#steps-for-collecting-logs-if-signoz-is-running-on-a-different-host
  #need to expose 2255 in signoz otel-collector in other host along with 4317,4318.
  # if don't want to use this, then https://pkg.go.dev/go.opentelemetry.io/contrib/bridges/otelslog is other option but won't be plug and play
  logspout:
    image: "gliderlabs/logspout:v3.2.14"
    container_name: signoz-logspout
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: syslog+tcp://10.211.55.4:2255
    # depends_on:
    #   - otel-collector
    restart: on-failure

networks:
  app-network:
