services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "5555:5555"
    environment:
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_NODE_RESOURCE_DETECTORS=env,host,os
      - OTEL_SERVICE_NAME=app-service
      - OTEL_EXPORTER_OTLP_INSECURE=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/localzone:/etc/localzone:ro
    depends_on:
      - otel-collector
    networks:
      - app-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config", "/etc/otel-collector-config.yaml"]
    container_name: otel-collector-container
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/localzone:/etc/localzone:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=10.211.55.4:4318
      - OTEL_EXPORTER_OTLP_INSECURE=true
    networks:
      - app-network

networks:
  app-network:
